// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package com.proto.greet;

public final class Greet {
  private Greet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greet_greeting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_greet_greeting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greet_greetingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_greet_greetingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greet_greetingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_greet_greetingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013greet.proto\022\005greet\"1\n\010greeting\022\022\n\nfirs" +
      "t_name\030\001 \001(\t\022\021\n\tlast_name\030\002 \001(\t\"4\n\017greet" +
      "ingRequest\022!\n\010greeting\030\001 \001(\0132\017.greet.gre" +
      "eting\"\"\n\020greetingResponse\022\016\n\006result\030\001 \001(" +
      "\t2\236\002\n\017greetingService\022:\n\005Greet\022\026.greet.g" +
      "reetingRequest\032\027.greet.greetingResponse\"" +
      "\000\022E\n\016GreetManyTimes\022\026.greet.greetingRequ" +
      "est\032\027.greet.greetingResponse\"\0000\001\022@\n\tLong" +
      "Greet\022\026.greet.greetingRequest\032\027.greet.gr" +
      "eetingResponse\"\000(\001\022F\n\rGreetEveryone\022\026.gr" +
      "eet.greetingRequest\032\027.greet.greetingResp" +
      "onse\"\000(\0010\001B\023\n\017com.proto.greetP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_greet_greeting_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_greet_greeting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_greet_greeting_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_greet_greetingRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_greet_greetingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_greet_greetingRequest_descriptor,
        new java.lang.String[] { "Greeting", });
    internal_static_greet_greetingResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_greet_greetingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_greet_greetingResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
