// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package com.proto.greet;

public interface greetingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.greeting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string first_name = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
