// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package com.proto.greet;

public interface greetingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.greetingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.greet.greeting greeting = 1;</code>
   */
  boolean hasGreeting();
  /**
   * <code>.greet.greeting greeting = 1;</code>
   */
  com.proto.greet.greeting getGreeting();
  /**
   * <code>.greet.greeting greeting = 1;</code>
   */
  com.proto.greet.greetingOrBuilder getGreetingOrBuilder();
}
