// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sum.proto

package com.proto.sum;

public interface InputValuesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sum.InputValues)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 num1 = 1;</code>
   */
  int getNum1();

  /**
   * <code>int32 num2 = 2;</code>
   */
  int getNum2();
}
