// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sum.proto

package com.proto.sum;

public interface SumRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sum.SumRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sum.InputValues values = 1;</code>
   */
  boolean hasValues();
  /**
   * <code>.sum.InputValues values = 1;</code>
   */
  com.proto.sum.InputValues getValues();
  /**
   * <code>.sum.InputValues values = 1;</code>
   */
  com.proto.sum.InputValuesOrBuilder getValuesOrBuilder();
}
