// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dummy.proto

package com.proto.dummy;

public interface dummyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dummy.dummyMessage)
    com.google.protobuf.MessageOrBuilder {
}
